<?php
$imageList = $block->getCustomerPhotos();
?>
<div class="customer-photos">
    <div class="customer-photos__container">
        <h2 class="customer-photos__title">Customer Gallery</h2>
                <div id="customer-photos-carousel" class="customer-photos__carousel">
                    <?php foreach($imageList as $item): ?>
                    <div class="customer-photos__item">
                        <div class="customer-photos__image-wrapper image-customer-photo">
                            <img class="customer-photos__image" data-lazy="<?=$item->getMediaPath() ?>" alt="<?=$item->getCustomerName() ?>">
                        </div>
                        <p class="customer-photos__name"><?=$item->getCustomerName() ?></p>
                        <?php if (!empty($item->getInstagram())) { ?><p class="customer-photos__instagram"><?=$item->getInstagram() ?></p><?php } ?>
                        <p class="customer-photos__wearing">wearing our</p>
                        <p class="customer-photos__product-link"><a href="<?=$item->getProductDetails()[1] ?>"><?=$item->getProductDetails()[0] ?></a></p>
                    </div>
                    <?php endforeach; ?>
                </div>
        <div class="customer-photos__actions">
            <button onclick="location.href='/customerphotos'" class="customer-photos__upload-btn">Upload your photo</button>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
{
    "#customer-photos-carousel": {
        "DreamSites_CustomerPhotos/js/customer-photos-carousel": {}
    }
}
</script>
