<?php
$imageList = $block->getCarouselImages();
?>
<section id="slick-carousel" class="hero__slider--section">
                <?php foreach($imageList as $item): ?>
                    <?php

                    $vertical = 'slick_position_bottom';
                    if ($item->getVerticalPosition() == 0) {
                        $vertical = 'slick_position_top';
                    } elseif ($item->getVerticalPosition() == 1) {
                        $vertical = 'slick_position_center';
                    }

                    $horizontal = 'slick_position_right';
                    if ($item->getHorizontalPosition() == 0) {
                        $horizontal = 'slick_position_left';
                    } elseif ($item->getHorizontalPosition() == 1) {
                        $horizontal = 'slick_position_middle';
                    }
                    ?>
                <!-- Single Slide Item -->
                <div class="slick-slide">
                    <div class="hero__slider--items <?= $vertical ?> <?= $horizontal ?>">
                        <!-- Placeholder Background Image -->
                        <div class="hero__slider--items__bg">
                            <img src="<?= $block->escapeUrl($item->getMediaPath()) ?>"
                                 alt="<?= $block->escapeHtmlAttr($item->getImageAlt()) ?>"
                                 class="hero__slider--items__img" />
                        </div>

                        <div class="container-fluid hero__slider--items__container">
                            <div class="hero__slider--items__inner">
                                <div class="row">
                                    <div class="slider__content">
                                        <!-- Main Heading -->
                                        <h2 class="slider__content--maintitle"
                                            style="color: <?= $item->getHeadingColour() ?> !important;">
                                            <?= $item->getHeading() ?>
                                        </h2>

                                        <!-- Sub Heading -->
                                        <p class="slider__content--desc"
                                            style="color: <?= $item->getTitleColour() ?> !important;">
                                            <?= $item->getTitle() ?>
                                        </p>

                                        <!-- CTA Button -->
                                        <div class="slider__content--btn">
                                            <a class="primary__btn carousel__btn"
                                               style="color: <?= $item->getButtonTextColour() ?> !important; background-color: <?= $item->getButtonColour() ?>;"
                                               href="<?= $item->getUrl() ?>">
                                                <span><?= $item->getButtonText() ?></span>
                                                <i class="fas fa-arrow-right primary__btn__icon"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
</section>
<script type="text/x-magento-init">
    {
        "#slick-carousel": {
            "DreamSites_HomeCarousel/js/carousel": {}
        }
    }
</script>
